function A = get_A(V,L1,L2,M,alpha,beta)
%get_A
%    A = get_A(V,L1,L2,M,ALPHA,BETA)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Nov-2022 16:24:26

t2 = abs(L1);
t3 = abs(alpha);
t4 = tan(alpha);
t7 = M.*1i;
t5 = abs(t4);
t6 = 1.0./t3;
t8 = 1.0./t5;
t9 = t2.*t8;
t10 = t7+t9;
t11 = angle(t10);
t12 = alpha.*t6.*t11;
A = (M.*V.*t4.*cos(beta+t12))./(L1.*L2.*sin(t12));
